name: Sync Main and Update Feature Branch

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight (UTC)
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3
        with:
          ref: main # Check out the main branch

      - name: Set Up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/EleutherAI/lm-evaluation-harness.git
          git fetch upstream

      - name: Sync with Upstream Main
        run: |
          git merge upstream/main --no-edit
          git push origin main

      - name: Checkout Feature Branch
        run: |
          git checkout vaxxstance
          git merge main --no-edit
          git push origin vaxxstance
